# Generated by Django 2.1.5 on 2019-01-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_point',
            field=models.IntegerField(default=0),
        ),
    ]
