# Generated by Django 2.1.5 on 2019-01-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('against', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True)),
                ('status', models.IntegerField(blank=True)),
                ('score', models.IntegerField(blank=True)),
                ('point', models.IntegerField(blank=True, default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='games',
            field=models.ManyToManyField(through='sport.TeamGame', to='sport.Game'),
        ),
    ]
