# Generated by Django 2.1.5 on 2019-01-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketSeasonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('twoscoreGoals', models.IntegerField(blank=True, null=True)),
                ('threescoreGoals', models.IntegerField(blank=True, null=True)),
                ('fault', models.IntegerField(blank=True, null=True)),
                ('ribsndhs', models.IntegerField(blank=True, null=True)),
                ('playTime', models.TimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FootBallSeasonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('goalPass', models.IntegerField(blank=True, null=True)),
                ('cards', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Profile')),
            ],
        ),
    ]
