# Generated by Django 2.1.5 on 2019-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballspringdetail',
            name='cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='footballspringdetail',
            name='goalPass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='footballspringdetail',
            name='goals',
            field=models.IntegerField(null=True),
        ),
    ]
