# Generated by Django 2.1.5 on 2019-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='favoriteGames',
            field=models.ManyToManyField(blank=True, null=True, to='sport.Game'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='favoriteNews',
            field=models.ManyToManyField(blank=True, null=True, to='sport.New'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/sport/users'),
        ),
    ]
