# Generated by Django 2.1.5 on 2019-01-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSpecialDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.IntegerField(blank=True)),
                ('team2', models.IntegerField(blank=True)),
                ('title', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1_corner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1_possession',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team1_shots',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_corner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_possession',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_shots',
        ),
        migrations.RemoveField(
            model_name='game_player',
            name='playerNumber',
        ),
        migrations.AddField(
            model_name='game',
            name='bestPlayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game_player',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Profile'),
        ),
        migrations.AddField(
            model_name='game_player',
            name='playTime',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gamespecialdetail',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Game'),
        ),
    ]
