# Generated by Django 2.1.5 on 2019-02-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20190201_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cup',
            old_name='teamnumber',
            new_name='team_number',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='teamnumber',
            new_name='team_number',
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(default='salam', on_delete=django.db.models.deletion.CASCADE, to='sport.Competition'),
            preserve_default=False,
        ),
    ]
