# Generated by Django 2.1.5 on 2019-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20190130_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='assets/sport/news'),
        ),
    ]
