# Generated by Django 2.1.5 on 2019-02-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20190130_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cup',
            name='match',
        ),
        migrations.RemoveField(
            model_name='league',
            name='match',
        ),
    ]
