# Generated by Django 2.1.5 on 2019-01-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20190125_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthDay',
            new_name='born',
        ),
        migrations.AddField(
            model_name='game_report',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_report',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sport.Game'),
        ),
    ]
