# Generated by Django 2.1.5 on 2019-01-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_basketseasondetail_footballseasondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='news',
            field=models.ManyToManyField(to='sport.New'),
        ),
    ]
