# Generated by Django 2.1.5 on 2019-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190127_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketseasondetail',
            name='playTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game_player',
            name='playTime',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
