# Generated by Django 2.1.5 on 2019-01-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190126_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favarites',
            field=models.ManyToManyField(null=True, to='sport.New'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/players'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previousClub',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='squad',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
