# Generated by Django 2.1.5 on 2019-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20190131_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='media1',
            field=models.FileField(blank=True, null=True, upload_to='assets/sport/games'),
        ),
        migrations.AlterField(
            model_name='game',
            name='media2',
            field=models.FileField(blank=True, null=True, upload_to='assets/sport/games'),
        ),
    ]
