# Generated by Django 2.1.5 on 2019-01-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_game_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='media1',
            field=models.FileField(null=True, upload_to='assets/sport/games'),
        ),
        migrations.AddField(
            model_name='game',
            name='media2',
            field=models.FileField(null=True, upload_to='assets/sport/games'),
        ),
    ]
