# Generated by Django 2.1.5 on 2019-01-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_auto_20190131_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
