# Generated by Django 2.1.5 on 2019-01-29 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0004_auto_20190129_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('bio', models.TextField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(null=True, upload_to='assets/sport/users')),
                ('favoriteGames', models.ManyToManyField(to='sport.Game')),
                ('favoriteNews', models.ManyToManyField(to='sport.New')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
