# Generated by Django 2.1.5 on 2019-02-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_auto_20190201_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bestPlayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, to='sport.New'),
        ),
    ]
