# Generated by Django 2.1.5 on 2019-01-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20190126_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/sport/team'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/sport/news'),
        ),
    ]
