# Generated by Django 2.1.5 on 2019-02-01 01:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20190201_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 1, 1, 44, 48, 450692, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='team1_score',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2_score',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
