# Generated by Django 2.1.5 on 2019-02-01 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20190201_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='teamnumber',
            field=models.IntegerField(blank=True, choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64), (128, 128)], default=16, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='teamnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cup',
            name='type',
            field=models.CharField(choices=[('F', 'FootBall'), ('B', 'BasketBall')], max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 1, 1, 59, 51, 351527, tzinfo=utc), null=True),
        ),
    ]
