# Generated by Django 2.1.5 on 2019-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_auto_20190129_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='relateds',
            field=models.ManyToManyField(to='sport.New'),
        ),
    ]
