# Generated by Django 2.1.5 on 2019-02-01 02:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_auto_20190201_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='league',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 1, 2, 19, 32, 946849, tzinfo=utc), null=True),
        ),
    ]
