# Generated by Django 2.1.5 on 2019-01-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_new_relateds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='relateds',
            field=models.ManyToManyField(null=True, to='sport.New'),
        ),
    ]
