# Generated by Django 2.1.5 on 2019-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20190129_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='relateds',
            field=models.ManyToManyField(blank=True, to='sport.New'),
        ),
    ]
