# Generated by Django 2.1.5 on 2019-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_auto_20190129_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='media',
            field=models.FileField(null=True, upload_to='assets/sport/news'),
        ),
    ]
