# Generated by Django 2.1.5 on 2019-02-01 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_auto_20190201_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('field', models.CharField(choices=[('F', 'FootBall'), ('B', 'BasketBall')], max_length=1)),
                ('current', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/sport/competition')),
            ],
        ),
        migrations.RemoveField(
            model_name='cup',
            name='current',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='type',
        ),
        migrations.RemoveField(
            model_name='league',
            name='current',
        ),
        migrations.RemoveField(
            model_name='league',
            name='id',
        ),
        migrations.RemoveField(
            model_name='league',
            name='image',
        ),
        migrations.RemoveField(
            model_name='league',
            name='name',
        ),
        migrations.RemoveField(
            model_name='league',
            name='type',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 1, 4, 5, 25, 213981, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='competition_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sport.Competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='competition_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sport.Competition'),
            preserve_default=False,
        ),
    ]
