# Generated by Django 2.1.5 on 2019-02-01 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0017_auto_20190201_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguerow',
            name='league',
        ),
    ]
