# Generated by Django 2.1.5 on 2019-02-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0018_remove_leaguerow_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguerow',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.League'),
        ),
    ]
